name: demo-workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Welcome greeting
        run: |
          echo "Welcome to the demo workflow"
          echo "first job is currently running"
      - name: Goodbye greeting
        run: |
          echo "first job has completed"
          echo "Bye for now"

      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1.5.0
